version: "1"

services:   
  mongo:
    image: mongo:latest
    container_name: dbparcial-mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=Unu#2025
    ports:
    - 27019:27017
    networks:
    - td2025 
    
networks:
  td2025:
    name: ms-unu

